import { z } from "zod";
import type { StatisticsSummary } from "./index.js";

export const CapabilityFlagsSchema = z.object({
  getDisplayMedia: z.boolean(),
  av1: z.boolean(),
  h265: z.boolean(),
  h264: z.boolean(),
  contentHint: z.boolean(),
  degradationPreference: z.boolean(),
  scaleResolutionDownBy: z.boolean(),
  jitterBufferTarget: z.boolean(),
  requestVideoFrameCallback: z.boolean(),
  encodedTransform: z.boolean(),
});
export type CapabilityFlags = z.infer<typeof CapabilityFlagsSchema>;

export function createCapabilityFlags(overrides: Partial<CapabilityFlags> = {}): CapabilityFlags {
  return {
    getDisplayMedia: false,
    av1: false,
    h265: false,
    h264: false,
    contentHint: false,
    degradationPreference: false,
    scaleResolutionDownBy: false,
    jitterBufferTarget: false,
    requestVideoFrameCallback: false,
    encodedTransform: false,
    ...overrides,
  };
}

export function createEmptyStatisticsSummary(): StatisticsSummary {
  return {
    codec: null,
    sourceWidth: null,
    sourceHeight: null,
    encodedWidth: null,
    encodedHeight: null,
    decodedWidth: null,
    decodedHeight: null,
    renderWidth: null,
    renderHeight: null,
    captureFps: null,
    previewFps: null,
    encodeFps: null,
    decodeFps: null,
    presentationFps: null,
    encoderTargetBitrateBps: null,
    targetBitrateBps: null,
    actualBitrateBps: null,
    availableOutgoingBitrateBps: null,
    framesEncoded: null,
    framesDecoded: null,
    keyFramesEncoded: null,
    keyFramesDecoded: null,
    packetSendDelayMsPerPacket: null,
    rttMs: null,
    minRttMs: null,
    rttTrendMs: null,
    jitterMs: null,
    jitterBufferDelayMs: null,
    jitterBufferTargetMs: null,
    packetLossPercent: null,
    packetsLost: null,
    nackCount: null,
    retransmittedPackets: null,
    pliCount: null,
    firCount: null,
    qpAverage: null,
    encodeTimeMsPerFrame: null,
    decodeTimeMsPerFrame: null,
    droppedFrames: null,
    freezeCount: null,
    freezeDurationMs: null,
    frameCadenceDeviationMs: null,
    estimatedLatencyMs: null,
    latencyP50Ms: null,
    latencyP95Ms: null,
    latencyP99Ms: null,
    clockOffsetMs: null,
    clockProbeRttMs: null,
    qualityLimitationReason: null,
    encoderImplementation: null,
    decoderImplementation: null,
    hdrMode: null,
    hdrStatus: null,
    displayHdrSupported: null,
    h264ProfileLevelId: null,
    requiredH264Level: null,
    encoderCapabilitySupported: null,
    encoderCapabilitySmooth: null,
    encoderCapabilityPowerEfficient: null,
    appliedMaxBitrateBps: null,
    appliedMaxFramerate: null,
    scaleResolutionDownBy: null,
    degradationPreference: null,
    mediaFlowState: null,
    transportState: null,
    iceState: null,
    dtlsState: null,
    candidatePairState: null,
    localCandidateCount: null,
    remoteCandidateCount: null,
    candidatePairCount: null,
    transportProtocol: null,
    serverBitrateBps: null,
    serverAvailableBitrateBps: null,
    serverRttMs: null,
    serverPacketLossPercent: null,
    serverScore: null,
    serverIceState: null,
    serverDtlsState: null,
    serverTransportProtocol: null,
    controllerState: null,
  };
}
